Create colaborador_template.md
openschoolbr/sobre pull request #7
Opened 2017-08-08 20:01 UTC by rlage

2017-08-08 20:08 UTC, khaosdoctor commented on colaborador_template.md
> +Seu perfil profissional e alguma informação sobre você
Aqui pode ser "Descrição" ou "Sobre você" no lugar de "Perfil"

2017-08-08 20:08 UTC, khaosdoctor commented on colaborador_template.md
> +## Gostaria colaborar em que área (veja as nossas áreas [aqui](#))?
Podemos colocar a lista de áreas e um documento MD descrevendo cada uma das funções que falamos na issue #13 do Fórum.

2017-08-08 20:08 UTC, khaosdoctor commented on colaborador_template.md
> +Area x, Area y
Aqui acho que pode ter a lista de todas as áreas que eu falei acima e ai o colaborador em questão apaga todas as linhas que não são da área que ele vai aplicar.

Por exemplo: O cara quer entrar como Redator no Medium, então ele apaga todas as linhas menos a de **Redator**

2017-08-08 20:09 UTC, khaosdoctor commented
Fiz algumas alterações no arquivo, acho que pode ser válido

2017-08-08 20:14 UTC, yuriploc commented on colaborador_template.md
> +Seu perfil profissional e alguma informação sobre você
Até porque pode ser que a pessoa ainda não tenha um perfil profissional..

2017-08-08 20:16 UTC, rlage commented
@khaosdoctor vcs conseguem commitar nesse PR?

2017-08-08 20:18 UTC, khaosdoctor commented
Consigo sim se você puder commitar agora melhor porque eu estou sem condições aqui, mas assim que chegar já posso atualizar para um modelo mais novo

2017-08-08 20:26 UTC, kvnol commented
Não sei vocês, mas não gosto desses underscores nos arquivos. Sou do time do hífen.

2017-08-08 21:01 UTC, rlage commented
@khaosdoctor não estou podendo não... qdo puder eu altero seguindo as sugestões... ou se alguém puder antes de mim, pode fazer tb.

@kvnol sobre o hifen ou underscore, para mim tanto faz rs

2017-08-08 23:33 UTC, khaosdoctor requested changes
Acho que alguns roles estão muito abertos

2017-08-08 23:33 UTC, khaosdoctor commented on colaborador_template.md
> +Organizer: pessoa do core da organização pra deixar tudo nos eixos (PRs, Moderação, Eventos)
Isso aqui acho que não deveria ser uma Role, porque é uma coisa que está intimamente ligada a organização e deveria ser tratada com mais cuidado do que deixar todos abertos para serem organizadores

2017-08-08 23:37 UTC, khaosdoctor commented
Adicionei minhas considerações no arquivo, vejam o que acham

2017-08-09 13:02 UTC, lflimeira commented
Nós aviamos definido o padrão hífen para os cursos, vamos seguir esse padrão conforme o @kvnol  disse?

2017-08-09 13:43 UTC, khaosdoctor commented
Sim, acho que deixar como `-` ao invés de `_` é melhor também... Sou do time do traço

2017-08-09 13:46 UTC, khaosdoctor commented
@kvnol @rlage @lflimeira @yuriploc O que acham agora? Está beleza?

2017-08-09 13:51 UTC, kvnol approved these changes
Lindo.

2017-08-09 13:55 UTC, rlage commented
Tá ótimo @khaosdoctor , valeu!

2017-08-09 14:13 UTC, khaosdoctor approved these changes

2017-08-09 14:13 UTC, merged

2017-08-09 14:13 UTC, khaosdoctor commented
Mesclado! :D