Create processo_colaborador.md
openschoolbr/sobre pull request #8
Opened 2017-08-08 20:13 UTC by rlage

2017-08-08 20:16 UTC, yuriploc approved these changes

2017-08-08 23:22 UTC, khaosdoctor requested changes
Tem uns pontos que eu fiquei com dúvida ali

2017-08-08 23:22 UTC, khaosdoctor commented on processo_colaborador.md
> +Antes de tudo, leia as responsabilidades do(a) Colaborador(a) e veja se está de acordo com isso. Em seguida leia toda essa sessão de como se tornar colaborador (a).
Existe algum link de responsabilidades que a gente pode colocar aqui?

2017-08-08 23:22 UTC, khaosdoctor commented on processo_colaborador.md
> +Basicamente você só precisa abrir um pull request nesse repositório adicionando seu perfil com os dados necessários conforme esse nosso [template](colaborador_template.md). Lembre-se que o nome do ar
A lista de colaboradores vai estar no README ou vai ser um outro arquivo?

2017-08-09 13:56 UTC, rlage commented on processo_colaborador.md
> +Basicamente você só precisa abrir um pull request nesse repositório adicionando seu perfil com os dados necessários conforme esse nosso [template](colaborador_template.md). Lembre-se que o nome do ar
Talvez seja melhor outro arquivo, para ficar mais organizado... e ai no README teria um link para esse arquivo

2017-08-09 13:57 UTC, rlage commented on processo_colaborador.md
> +Antes de tudo, leia as responsabilidades do(a) Colaborador(a) e veja se está de acordo com isso. Em seguida leia toda essa sessão de como se tornar colaborador (a).
Não, mas talvez a gente possa copiar o código de conduta lá do training center.

2017-08-09 14:13 UTC, khaosdoctor commented on processo_colaborador.md
> +Antes de tudo, leia as responsabilidades do(a) Colaborador(a) e veja se está de acordo com isso. Em seguida leia toda essa sessão de como se tornar colaborador (a).
Vamos adicionar nessa PR o arquivo então, acho melhor

2017-08-09 14:14 UTC, khaosdoctor commented on processo_colaborador.md
> +Basicamente você só precisa abrir um pull request nesse repositório adicionando seu perfil com os dados necessários conforme esse nosso [template](colaborador_template.md). Lembre-se que o nome do ar
Vamos criar todos juntos nessa aqui, para ficar mais fácil

2017-08-09 19:37 UTC, khaosdoctor approved these changes

2017-08-09 19:38 UTC, khaosdoctor commented
Vou mesclar essa PR porque precisamos criar os arquivos extras, então é mais simples já adicionarmos aqui tudo para podermos criar o Code Of Conduct e também o README com a lista de membros

2017-08-09 19:38 UTC, merged